name:                ghcprofview
version:             0.1.0.0
github:              "portnov/ghcprofview-hs"
license:             BSD3
author:              "Ilya V. Portnov"
maintainer:          "portnov84@rambler.ru"
copyright:           "2019 Ilya V. Portnov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            GHC .prof files viewer
category:            Development

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/portnov/ghcprofview-hs#readme>

dependencies:
- base >= 4.7 && < 5
- mtl >= 2.2
- containers
- text
- aeson
- scientific
- regex-tdfa
- ghc-prof
- haskell-gi-base
- gi-gtk

executables:
  ghcprofview:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -fwarn-unused-imports
    - -with-rtsopts=-N
    - -O2
